COMMENT ON TABLE public.app_config IS 'Configuración de aplicación; super_admin_email define el correo del super administrador';
COMMENT ON TABLE public.asambleas IS 'Almacena las asambleas de copropietarios';
COMMENT ON TABLE public.billing_logs IS 'Auditoría de cobro: cada descuento o acreditación de tokens del gestor';
COMMENT ON TABLE public.configuracion_asamblea IS 'Preferencias de visualización de asamblea por usuario y conjunto; default del cronómetro (minutos)';
COMMENT ON TABLE public.configuracion_global IS 'Configuración global (landing: título, subtítulo, WhatsApp) editable desde Super Admin';
COMMENT ON TABLE public.configuracion_legal IS 'Documentos legales editables desde Super Admin';
COMMENT ON TABLE public.configuracion_poderes IS 'Configuración de límites para poderes por conjunto';
COMMENT ON TABLE public.configuracion_smtp IS 'Configuración SMTP para envío de correo (enlace de votación). Editable solo por Super Admin. Solo service_role puede leer/escribir.';
COMMENT ON TABLE public.configuracion_whatsapp IS 'Configuración WhatsApp Business API (Meta). Token, Phone Number ID, plantilla y tokens a descontar por mensaje.';
COMMENT ON TABLE public.consentimiento_tratamiento_datos IS 'Aceptación del tratamiento de datos personales por votante y asamblea (Ley 1581 de 2012, LOPD)';
COMMENT ON TABLE public.historial_votos IS 'Registro completo de todos los votos y modificaciones (trazabilidad Ley 675)';
COMMENT ON TABLE public.opciones_pregunta IS 'Opciones de respuesta para cada pregunta de votación';
COMMENT ON TABLE public.organizations IS 'Tabla de copropiedades para gestion de asambleas';
COMMENT ON TABLE public.pagos_checkout_ref IS 'Mapeo ref (sku del link Wompi) -> user_id para acreditar tokens en el webhook';
COMMENT ON TABLE public.pagos_historial IS 'Historial de transacciones de pago confirmadas por conjunto';
COMMENT ON TABLE public.pagos_log IS 'Log de transacciones Wompi por conjunto';
COMMENT ON TABLE public.planes IS 'Planes (free, pro, pilot) con nombre y precio; editable desde super-admin';
COMMENT ON TABLE public.poderes IS 'Poderes otorgados entre propietarios para votar en asambleas';
COMMENT ON TABLE public.preguntas IS 'Preguntas de votación para cada asamblea';
COMMENT ON TABLE public.puntos_orden_dia IS 'Puntos del orden del día (agenda); las preguntas pueden asociarse opcionalmente a un punto.';
COMMENT ON TABLE public.quorum_asamblea IS 'Registro de asistencia (física o virtual) a asambleas';
COMMENT ON TABLE public.sesion_token_consumos IS 'Cobro LOPD por unidad y sesión; evita doble cobro multi-dispositivo (UNIQUE asamblea+seq+unidad)';
COMMENT ON TABLE public.super_admin_accounts IS 'Listado de super admins adicionales gestionables desde la app.';
COMMENT ON TABLE public.verificacion_asamblea_sesiones IS 'Cada fila = una vez que se abrió la verificación de asistencia (asamblea en general). Al cerrar se rellena cierre_at y el snapshot.';
COMMENT ON TABLE public.verificacion_asistencia_registro IS 'Una fila por (unidad en asamblea, contexto). pregunta_id null = verificación general; no null = verificación asociada a esa pregunta.';
COMMENT ON TABLE public.votos IS 'Registro de todos los votos emitidos en asambleas';
