ALTER TABLE public.app_config DROP CONSTRAINT IF EXISTS app_config_pkey;
ALTER TABLE public.app_config ADD CONSTRAINT app_config_pkey PRIMARY KEY (key);
ALTER TABLE public.asambleas DROP CONSTRAINT IF EXISTS asambleas_codigo_acceso_key;
ALTER TABLE public.asambleas ADD CONSTRAINT asambleas_codigo_acceso_key UNIQUE (codigo_acceso);
ALTER TABLE public.asambleas DROP CONSTRAINT IF EXISTS asambleas_estado_check;
ALTER TABLE public.asambleas ADD CONSTRAINT asambleas_estado_check CHECK (estado = ANY (ARRAY['borrador'::text, 'activa'::text, 'finalizada'::text]));
ALTER TABLE public.asambleas DROP CONSTRAINT IF EXISTS asambleas_organization_id_fkey;
ALTER TABLE public.asambleas ADD CONSTRAINT asambleas_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.asambleas DROP CONSTRAINT IF EXISTS asambleas_pkey;
ALTER TABLE public.asambleas ADD CONSTRAINT asambleas_pkey PRIMARY KEY (id);
ALTER TABLE public.asambleas DROP CONSTRAINT IF EXISTS asambleas_punto_orden_dia_actual_id_fkey;
ALTER TABLE public.asambleas ADD CONSTRAINT asambleas_punto_orden_dia_actual_id_fkey FOREIGN KEY (punto_orden_dia_actual_id) REFERENCES puntos_orden_dia(id) ON DELETE SET NULL;
ALTER TABLE public.asambleas DROP CONSTRAINT IF EXISTS asambleas_session_mode_check;
ALTER TABLE public.asambleas ADD CONSTRAINT asambleas_session_mode_check CHECK (session_mode = ANY (ARRAY['inactive'::text, 'verification'::text, 'voting'::text]));
ALTER TABLE public.asambleas DROP CONSTRAINT IF EXISTS asambleas_verificacion_pregunta_id_fkey;
ALTER TABLE public.asambleas ADD CONSTRAINT asambleas_verificacion_pregunta_id_fkey FOREIGN KEY (verificacion_pregunta_id) REFERENCES preguntas(id) ON DELETE SET NULL;
ALTER TABLE public.billing_logs DROP CONSTRAINT IF EXISTS billing_logs_pkey;
ALTER TABLE public.billing_logs ADD CONSTRAINT billing_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.billing_logs DROP CONSTRAINT IF EXISTS billing_logs_tipo_operacion_check;
ALTER TABLE public.billing_logs ADD CONSTRAINT billing_logs_tipo_operacion_check CHECK (tipo_operacion = ANY (ARRAY['Acta'::text, 'Votación'::text, 'Registro_manual'::text, 'Compra'::text, 'Ajuste_manual'::text, 'WhatsApp'::text, 'Consentimiento_sesion'::text]));
ALTER TABLE public.configuracion_asamblea DROP CONSTRAINT IF EXISTS configuracion_asamblea_organization_id_fkey;
ALTER TABLE public.configuracion_asamblea ADD CONSTRAINT configuracion_asamblea_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.configuracion_asamblea DROP CONSTRAINT IF EXISTS configuracion_asamblea_pkey;
ALTER TABLE public.configuracion_asamblea ADD CONSTRAINT configuracion_asamblea_pkey PRIMARY KEY (id);
ALTER TABLE public.configuracion_asamblea DROP CONSTRAINT IF EXISTS configuracion_asamblea_user_id_fkey;
ALTER TABLE public.configuracion_asamblea ADD CONSTRAINT configuracion_asamblea_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.configuracion_asamblea DROP CONSTRAINT IF EXISTS configuracion_asamblea_user_id_organization_id_key;
ALTER TABLE public.configuracion_asamblea ADD CONSTRAINT configuracion_asamblea_user_id_organization_id_key UNIQUE (user_id, organization_id);
ALTER TABLE public.configuracion_global DROP CONSTRAINT IF EXISTS configuracion_global_key_key;
ALTER TABLE public.configuracion_global ADD CONSTRAINT configuracion_global_key_key UNIQUE (key);
ALTER TABLE public.configuracion_global DROP CONSTRAINT IF EXISTS configuracion_global_pkey;
ALTER TABLE public.configuracion_global ADD CONSTRAINT configuracion_global_pkey PRIMARY KEY (id);
ALTER TABLE public.configuracion_legal DROP CONSTRAINT IF EXISTS configuracion_legal_doc_key_key;
ALTER TABLE public.configuracion_legal ADD CONSTRAINT configuracion_legal_doc_key_key UNIQUE (doc_key);
ALTER TABLE public.configuracion_legal DROP CONSTRAINT IF EXISTS configuracion_legal_pkey;
ALTER TABLE public.configuracion_legal ADD CONSTRAINT configuracion_legal_pkey PRIMARY KEY (id);
ALTER TABLE public.configuracion_poderes DROP CONSTRAINT IF EXISTS configuracion_poderes_organization_id_fkey;
ALTER TABLE public.configuracion_poderes ADD CONSTRAINT configuracion_poderes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.configuracion_poderes DROP CONSTRAINT IF EXISTS configuracion_poderes_organization_id_key;
ALTER TABLE public.configuracion_poderes ADD CONSTRAINT configuracion_poderes_organization_id_key UNIQUE (organization_id);
ALTER TABLE public.configuracion_poderes DROP CONSTRAINT IF EXISTS configuracion_poderes_pkey;
ALTER TABLE public.configuracion_poderes ADD CONSTRAINT configuracion_poderes_pkey PRIMARY KEY (id);
ALTER TABLE public.configuracion_smtp DROP CONSTRAINT IF EXISTS configuracion_smtp_key_key;
ALTER TABLE public.configuracion_smtp ADD CONSTRAINT configuracion_smtp_key_key UNIQUE (key);
ALTER TABLE public.configuracion_smtp DROP CONSTRAINT IF EXISTS configuracion_smtp_pkey;
ALTER TABLE public.configuracion_smtp ADD CONSTRAINT configuracion_smtp_pkey PRIMARY KEY (id);
ALTER TABLE public.configuracion_whatsapp DROP CONSTRAINT IF EXISTS configuracion_whatsapp_key_key;
ALTER TABLE public.configuracion_whatsapp ADD CONSTRAINT configuracion_whatsapp_key_key UNIQUE (key);
ALTER TABLE public.configuracion_whatsapp DROP CONSTRAINT IF EXISTS configuracion_whatsapp_pkey;
ALTER TABLE public.configuracion_whatsapp ADD CONSTRAINT configuracion_whatsapp_pkey PRIMARY KEY (id);
ALTER TABLE public.consentimiento_tratamiento_datos DROP CONSTRAINT IF EXISTS consentimiento_tratamiento_datos_asamblea_id_fkey;
ALTER TABLE public.consentimiento_tratamiento_datos ADD CONSTRAINT consentimiento_tratamiento_datos_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.consentimiento_tratamiento_datos DROP CONSTRAINT IF EXISTS consentimiento_tratamiento_datos_asamblea_ident_session_uq;
ALTER TABLE public.consentimiento_tratamiento_datos ADD CONSTRAINT consentimiento_tratamiento_datos_asamblea_ident_session_uq UNIQUE (asamblea_id, identificador, session_seq);
ALTER TABLE public.consentimiento_tratamiento_datos DROP CONSTRAINT IF EXISTS consentimiento_tratamiento_datos_pkey;
ALTER TABLE public.consentimiento_tratamiento_datos ADD CONSTRAINT consentimiento_tratamiento_datos_pkey PRIMARY KEY (id);
ALTER TABLE public.historial_votos DROP CONSTRAINT IF EXISTS historial_votos_accion_check;
ALTER TABLE public.historial_votos ADD CONSTRAINT historial_votos_accion_check CHECK (accion = ANY (ARRAY['crear'::text, 'modificar'::text]));
ALTER TABLE public.historial_votos DROP CONSTRAINT IF EXISTS historial_votos_opcion_anterior_id_fkey;
ALTER TABLE public.historial_votos ADD CONSTRAINT historial_votos_opcion_anterior_id_fkey FOREIGN KEY (opcion_anterior_id) REFERENCES opciones_pregunta(id);
ALTER TABLE public.historial_votos DROP CONSTRAINT IF EXISTS historial_votos_opcion_id_fkey;
ALTER TABLE public.historial_votos ADD CONSTRAINT historial_votos_opcion_id_fkey FOREIGN KEY (opcion_id) REFERENCES opciones_pregunta(id) ON DELETE CASCADE;
ALTER TABLE public.historial_votos DROP CONSTRAINT IF EXISTS historial_votos_pkey;
ALTER TABLE public.historial_votos ADD CONSTRAINT historial_votos_pkey PRIMARY KEY (id);
ALTER TABLE public.historial_votos DROP CONSTRAINT IF EXISTS historial_votos_poder_id_fkey;
ALTER TABLE public.historial_votos ADD CONSTRAINT historial_votos_poder_id_fkey FOREIGN KEY (poder_id) REFERENCES poderes(id);
ALTER TABLE public.historial_votos DROP CONSTRAINT IF EXISTS historial_votos_pregunta_id_fkey;
ALTER TABLE public.historial_votos ADD CONSTRAINT historial_votos_pregunta_id_fkey FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) ON DELETE CASCADE;
ALTER TABLE public.historial_votos DROP CONSTRAINT IF EXISTS historial_votos_unidad_id_fkey;
ALTER TABLE public.historial_votos ADD CONSTRAINT historial_votos_unidad_id_fkey FOREIGN KEY (unidad_id) REFERENCES unidades(id) ON DELETE CASCADE;
ALTER TABLE public.historial_votos DROP CONSTRAINT IF EXISTS historial_votos_voto_id_fkey;
ALTER TABLE public.historial_votos ADD CONSTRAINT historial_votos_voto_id_fkey FOREIGN KEY (voto_id) REFERENCES votos(id) ON DELETE CASCADE;
ALTER TABLE public.opciones_pregunta DROP CONSTRAINT IF EXISTS opciones_pregunta_pkey;
ALTER TABLE public.opciones_pregunta ADD CONSTRAINT opciones_pregunta_pkey PRIMARY KEY (id);
ALTER TABLE public.opciones_pregunta DROP CONSTRAINT IF EXISTS opciones_pregunta_pregunta_id_fkey;
ALTER TABLE public.opciones_pregunta ADD CONSTRAINT opciones_pregunta_pregunta_id_fkey FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) ON DELETE CASCADE;
ALTER TABLE public.organizations DROP CONSTRAINT IF EXISTS organizations_owner_id_fkey;
ALTER TABLE public.organizations ADD CONSTRAINT organizations_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id);
ALTER TABLE public.organizations DROP CONSTRAINT IF EXISTS organizations_pkey;
ALTER TABLE public.organizations ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);
ALTER TABLE public.organizations DROP CONSTRAINT IF EXISTS organizations_slug_key;
ALTER TABLE public.organizations ADD CONSTRAINT organizations_slug_key UNIQUE (slug);
ALTER TABLE public.organizations DROP CONSTRAINT IF EXISTS unique_organization_nit;
ALTER TABLE public.organizations ADD CONSTRAINT unique_organization_nit UNIQUE (nit);
ALTER TABLE public.pagos_checkout_ref DROP CONSTRAINT IF EXISTS pagos_checkout_ref_pkey;
ALTER TABLE public.pagos_checkout_ref ADD CONSTRAINT pagos_checkout_ref_pkey PRIMARY KEY (ref);
ALTER TABLE public.pagos_historial DROP CONSTRAINT IF EXISTS pagos_historial_organization_id_fkey;
ALTER TABLE public.pagos_historial ADD CONSTRAINT pagos_historial_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pagos_historial DROP CONSTRAINT IF EXISTS pagos_historial_pkey;
ALTER TABLE public.pagos_historial ADD CONSTRAINT pagos_historial_pkey PRIMARY KEY (id);
ALTER TABLE public.pagos_historial DROP CONSTRAINT IF EXISTS pagos_historial_status_check;
ALTER TABLE public.pagos_historial ADD CONSTRAINT pagos_historial_status_check CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'failed'::text, 'refunded'::text]));
ALTER TABLE public.pagos_log DROP CONSTRAINT IF EXISTS pagos_log_organization_id_fkey;
ALTER TABLE public.pagos_log ADD CONSTRAINT pagos_log_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pagos_log DROP CONSTRAINT IF EXISTS pagos_log_pkey;
ALTER TABLE public.pagos_log ADD CONSTRAINT pagos_log_pkey PRIMARY KEY (id);
ALTER TABLE public.pagos_log DROP CONSTRAINT IF EXISTS pagos_log_user_id_fkey;
ALTER TABLE public.pagos_log ADD CONSTRAINT pagos_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.planes DROP CONSTRAINT IF EXISTS planes_key_key;
ALTER TABLE public.planes ADD CONSTRAINT planes_key_key UNIQUE (key);
ALTER TABLE public.planes DROP CONSTRAINT IF EXISTS planes_pkey;
ALTER TABLE public.planes ADD CONSTRAINT planes_pkey PRIMARY KEY (id);
ALTER TABLE public.poderes DROP CONSTRAINT IF EXISTS poderes_asamblea_id_fkey;
ALTER TABLE public.poderes ADD CONSTRAINT poderes_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.poderes DROP CONSTRAINT IF EXISTS poderes_estado_check;
ALTER TABLE public.poderes ADD CONSTRAINT poderes_estado_check CHECK (estado = ANY (ARRAY['activo'::text, 'revocado'::text, 'usado'::text, 'pendiente_verificacion'::text]));
ALTER TABLE public.poderes DROP CONSTRAINT IF EXISTS poderes_pkey;
ALTER TABLE public.poderes ADD CONSTRAINT poderes_pkey PRIMARY KEY (id);
ALTER TABLE public.poderes DROP CONSTRAINT IF EXISTS poderes_unidad_otorgante_id_fkey;
ALTER TABLE public.poderes ADD CONSTRAINT poderes_unidad_otorgante_id_fkey FOREIGN KEY (unidad_otorgante_id) REFERENCES unidades(id) ON DELETE CASCADE;
ALTER TABLE public.poderes DROP CONSTRAINT IF EXISTS poderes_unidad_receptor_id_fkey;
ALTER TABLE public.poderes ADD CONSTRAINT poderes_unidad_receptor_id_fkey FOREIGN KEY (unidad_receptor_id) REFERENCES unidades(id) ON DELETE CASCADE;
ALTER TABLE public.preguntas DROP CONSTRAINT IF EXISTS preguntas_asamblea_id_fkey;
ALTER TABLE public.preguntas ADD CONSTRAINT preguntas_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.preguntas DROP CONSTRAINT IF EXISTS preguntas_estado_check;
ALTER TABLE public.preguntas ADD CONSTRAINT preguntas_estado_check CHECK (estado = ANY (ARRAY['pendiente'::text, 'abierta'::text, 'cerrada'::text]));
ALTER TABLE public.preguntas DROP CONSTRAINT IF EXISTS preguntas_pkey;
ALTER TABLE public.preguntas ADD CONSTRAINT preguntas_pkey PRIMARY KEY (id);
ALTER TABLE public.preguntas DROP CONSTRAINT IF EXISTS preguntas_punto_orden_dia_id_fkey;
ALTER TABLE public.preguntas ADD CONSTRAINT preguntas_punto_orden_dia_id_fkey FOREIGN KEY (punto_orden_dia_id) REFERENCES puntos_orden_dia(id) ON DELETE SET NULL;
ALTER TABLE public.preguntas DROP CONSTRAINT IF EXISTS preguntas_tipo_votacion_check;
ALTER TABLE public.preguntas ADD CONSTRAINT preguntas_tipo_votacion_check CHECK (tipo_votacion = ANY (ARRAY['coeficiente'::text, 'nominal'::text]));
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_new_organization_id_fkey;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_new_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_new_pkey;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_new_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_new_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_new_role_check CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text]));
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_new_user_id_fkey;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_new_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_new_user_id_organization_id_key;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_new_user_id_organization_id_key UNIQUE (user_id, organization_id);
ALTER TABLE public.profiles_temp DROP CONSTRAINT IF EXISTS profiles_temp_organization_id_fkey;
ALTER TABLE public.profiles_temp ADD CONSTRAINT profiles_temp_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.profiles_temp DROP CONSTRAINT IF EXISTS profiles_temp_pkey;
ALTER TABLE public.profiles_temp ADD CONSTRAINT profiles_temp_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles_temp DROP CONSTRAINT IF EXISTS profiles_temp_role_check;
ALTER TABLE public.profiles_temp ADD CONSTRAINT profiles_temp_role_check CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text]));
ALTER TABLE public.profiles_temp DROP CONSTRAINT IF EXISTS profiles_temp_user_id_fkey;
ALTER TABLE public.profiles_temp ADD CONSTRAINT profiles_temp_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles_temp DROP CONSTRAINT IF EXISTS profiles_temp_user_id_organization_id_key;
ALTER TABLE public.profiles_temp ADD CONSTRAINT profiles_temp_user_id_organization_id_key UNIQUE (user_id, organization_id);
ALTER TABLE public.puntos_orden_dia DROP CONSTRAINT IF EXISTS puntos_orden_dia_asamblea_id_fkey;
ALTER TABLE public.puntos_orden_dia ADD CONSTRAINT puntos_orden_dia_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.puntos_orden_dia DROP CONSTRAINT IF EXISTS puntos_orden_dia_pkey;
ALTER TABLE public.puntos_orden_dia ADD CONSTRAINT puntos_orden_dia_pkey PRIMARY KEY (id);
ALTER TABLE public.quorum_asamblea DROP CONSTRAINT IF EXISTS quorum_asamblea_asamblea_id_fkey;
ALTER TABLE public.quorum_asamblea ADD CONSTRAINT quorum_asamblea_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.quorum_asamblea DROP CONSTRAINT IF EXISTS quorum_asamblea_asamblea_id_unidad_id_key;
ALTER TABLE public.quorum_asamblea ADD CONSTRAINT quorum_asamblea_asamblea_id_unidad_id_key UNIQUE (asamblea_id, unidad_id);
ALTER TABLE public.quorum_asamblea DROP CONSTRAINT IF EXISTS quorum_asamblea_pkey;
ALTER TABLE public.quorum_asamblea ADD CONSTRAINT quorum_asamblea_pkey PRIMARY KEY (id);
ALTER TABLE public.quorum_asamblea DROP CONSTRAINT IF EXISTS quorum_asamblea_unidad_id_fkey;
ALTER TABLE public.quorum_asamblea ADD CONSTRAINT quorum_asamblea_unidad_id_fkey FOREIGN KEY (unidad_id) REFERENCES unidades(id) ON DELETE CASCADE;
ALTER TABLE public.quorum_event_log DROP CONSTRAINT IF EXISTS quorum_event_log_asamblea_id_fkey;
ALTER TABLE public.quorum_event_log ADD CONSTRAINT quorum_event_log_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.quorum_event_log DROP CONSTRAINT IF EXISTS quorum_event_log_asamblea_id_idempotency_key_key;
ALTER TABLE public.quorum_event_log ADD CONSTRAINT quorum_event_log_asamblea_id_idempotency_key_key UNIQUE (asamblea_id, idempotency_key);
ALTER TABLE public.quorum_event_log DROP CONSTRAINT IF EXISTS quorum_event_log_pkey;
ALTER TABLE public.quorum_event_log ADD CONSTRAINT quorum_event_log_pkey PRIMARY KEY (id);
ALTER TABLE public.quorum_event_log DROP CONSTRAINT IF EXISTS quorum_event_log_pregunta_id_fkey;
ALTER TABLE public.quorum_event_log ADD CONSTRAINT quorum_event_log_pregunta_id_fkey FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) ON DELETE SET NULL;
ALTER TABLE public.quorum_event_log DROP CONSTRAINT IF EXISTS quorum_event_log_presence_id_fkey;
ALTER TABLE public.quorum_event_log ADD CONSTRAINT quorum_event_log_presence_id_fkey FOREIGN KEY (presence_id) REFERENCES quorum_presence(id) ON DELETE SET NULL;
ALTER TABLE public.quorum_presence DROP CONSTRAINT IF EXISTS quorum_presence_asamblea_id_fkey;
ALTER TABLE public.quorum_presence ADD CONSTRAINT quorum_presence_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.quorum_presence DROP CONSTRAINT IF EXISTS quorum_presence_asamblea_id_participant_key_key;
ALTER TABLE public.quorum_presence ADD CONSTRAINT quorum_presence_asamblea_id_participant_key_key UNIQUE (asamblea_id, participant_key);
ALTER TABLE public.quorum_presence DROP CONSTRAINT IF EXISTS quorum_presence_pkey;
ALTER TABLE public.quorum_presence ADD CONSTRAINT quorum_presence_pkey PRIMARY KEY (id);
ALTER TABLE public.quorum_presence_config DROP CONSTRAINT IF EXISTS quorum_presence_config_asamblea_id_fkey;
ALTER TABLE public.quorum_presence_config ADD CONSTRAINT quorum_presence_config_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.quorum_presence_config DROP CONSTRAINT IF EXISTS quorum_presence_config_heartbeat_interval_seconds_check;
ALTER TABLE public.quorum_presence_config ADD CONSTRAINT quorum_presence_config_heartbeat_interval_seconds_check CHECK (heartbeat_interval_seconds >= 5 AND heartbeat_interval_seconds <= 120);
ALTER TABLE public.quorum_presence_config DROP CONSTRAINT IF EXISTS quorum_presence_config_idle_after_seconds_check;
ALTER TABLE public.quorum_presence_config ADD CONSTRAINT quorum_presence_config_idle_after_seconds_check CHECK (idle_after_seconds >= 15 AND idle_after_seconds <= 900);
ALTER TABLE public.quorum_presence_config DROP CONSTRAINT IF EXISTS quorum_presence_config_offline_after_seconds_check;
ALTER TABLE public.quorum_presence_config ADD CONSTRAINT quorum_presence_config_offline_after_seconds_check CHECK (offline_after_seconds >= 60 AND offline_after_seconds <= 3600);
ALTER TABLE public.quorum_presence_config DROP CONSTRAINT IF EXISTS quorum_presence_config_pkey;
ALTER TABLE public.quorum_presence_config ADD CONSTRAINT quorum_presence_config_pkey PRIMARY KEY (asamblea_id);
ALTER TABLE public.quorum_presence_config DROP CONSTRAINT IF EXISTS quorum_presence_config_stale_after_seconds_check;
ALTER TABLE public.quorum_presence_config ADD CONSTRAINT quorum_presence_config_stale_after_seconds_check CHECK (stale_after_seconds >= 30 AND stale_after_seconds <= 1800);
ALTER TABLE public.quorum_presence_units DROP CONSTRAINT IF EXISTS quorum_presence_units_pkey;
ALTER TABLE public.quorum_presence_units ADD CONSTRAINT quorum_presence_units_pkey PRIMARY KEY (id);
ALTER TABLE public.quorum_presence_units DROP CONSTRAINT IF EXISTS quorum_presence_units_poder_id_fkey;
ALTER TABLE public.quorum_presence_units ADD CONSTRAINT quorum_presence_units_poder_id_fkey FOREIGN KEY (poder_id) REFERENCES poderes(id) ON DELETE SET NULL;
ALTER TABLE public.quorum_presence_units DROP CONSTRAINT IF EXISTS quorum_presence_units_presence_id_fkey;
ALTER TABLE public.quorum_presence_units ADD CONSTRAINT quorum_presence_units_presence_id_fkey FOREIGN KEY (presence_id) REFERENCES quorum_presence(id) ON DELETE CASCADE;
ALTER TABLE public.quorum_presence_units DROP CONSTRAINT IF EXISTS quorum_presence_units_presence_id_unidad_id_key;
ALTER TABLE public.quorum_presence_units ADD CONSTRAINT quorum_presence_units_presence_id_unidad_id_key UNIQUE (presence_id, unidad_id);
ALTER TABLE public.quorum_presence_units DROP CONSTRAINT IF EXISTS quorum_presence_units_unidad_id_fkey;
ALTER TABLE public.quorum_presence_units ADD CONSTRAINT quorum_presence_units_unidad_id_fkey FOREIGN KEY (unidad_id) REFERENCES unidades(id) ON DELETE CASCADE;
ALTER TABLE public.quorum_snapshot DROP CONSTRAINT IF EXISTS quorum_snapshot_asamblea_id_fkey;
ALTER TABLE public.quorum_snapshot ADD CONSTRAINT quorum_snapshot_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.quorum_snapshot DROP CONSTRAINT IF EXISTS quorum_snapshot_generated_by_event_id_fkey;
ALTER TABLE public.quorum_snapshot ADD CONSTRAINT quorum_snapshot_generated_by_event_id_fkey FOREIGN KEY (generated_by_event_id) REFERENCES quorum_event_log(id) ON DELETE SET NULL;
ALTER TABLE public.quorum_snapshot DROP CONSTRAINT IF EXISTS quorum_snapshot_pkey;
ALTER TABLE public.quorum_snapshot ADD CONSTRAINT quorum_snapshot_pkey PRIMARY KEY (id);
ALTER TABLE public.quorum_snapshot DROP CONSTRAINT IF EXISTS quorum_snapshot_pregunta_id_fkey;
ALTER TABLE public.quorum_snapshot ADD CONSTRAINT quorum_snapshot_pregunta_id_fkey FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) ON DELETE SET NULL;
ALTER TABLE public.sesion_token_consumos DROP CONSTRAINT IF EXISTS sesion_token_consumos_asamblea_id_fkey;
ALTER TABLE public.sesion_token_consumos ADD CONSTRAINT sesion_token_consumos_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.sesion_token_consumos DROP CONSTRAINT IF EXISTS sesion_token_consumos_asamblea_id_session_seq_unidad_id_key;
ALTER TABLE public.sesion_token_consumos ADD CONSTRAINT sesion_token_consumos_asamblea_id_session_seq_unidad_id_key UNIQUE (asamblea_id, session_seq, unidad_id);
ALTER TABLE public.sesion_token_consumos DROP CONSTRAINT IF EXISTS sesion_token_consumos_consentimiento_id_fkey;
ALTER TABLE public.sesion_token_consumos ADD CONSTRAINT sesion_token_consumos_consentimiento_id_fkey FOREIGN KEY (consentimiento_id) REFERENCES consentimiento_tratamiento_datos(id) ON DELETE SET NULL;
ALTER TABLE public.sesion_token_consumos DROP CONSTRAINT IF EXISTS sesion_token_consumos_pkey;
ALTER TABLE public.sesion_token_consumos ADD CONSTRAINT sesion_token_consumos_pkey PRIMARY KEY (id);
ALTER TABLE public.sesion_token_consumos DROP CONSTRAINT IF EXISTS sesion_token_consumos_tokens_cobrados_check;
ALTER TABLE public.sesion_token_consumos ADD CONSTRAINT sesion_token_consumos_tokens_cobrados_check CHECK (tokens_cobrados >= 0);
ALTER TABLE public.sesion_token_consumos DROP CONSTRAINT IF EXISTS sesion_token_consumos_unidad_id_fkey;
ALTER TABLE public.sesion_token_consumos ADD CONSTRAINT sesion_token_consumos_unidad_id_fkey FOREIGN KEY (unidad_id) REFERENCES unidades(id) ON DELETE CASCADE;
ALTER TABLE public.super_admin_accounts DROP CONSTRAINT IF EXISTS super_admin_accounts_email_key;
ALTER TABLE public.super_admin_accounts ADD CONSTRAINT super_admin_accounts_email_key UNIQUE (email);
ALTER TABLE public.super_admin_accounts DROP CONSTRAINT IF EXISTS super_admin_accounts_pkey;
ALTER TABLE public.super_admin_accounts ADD CONSTRAINT super_admin_accounts_pkey PRIMARY KEY (id);
ALTER TABLE public.unidades DROP CONSTRAINT IF EXISTS unidades_organization_id_fkey;
ALTER TABLE public.unidades ADD CONSTRAINT unidades_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.unidades DROP CONSTRAINT IF EXISTS unidades_pkey;
ALTER TABLE public.unidades ADD CONSTRAINT unidades_pkey PRIMARY KEY (id);
ALTER TABLE public.unidades DROP CONSTRAINT IF EXISTS unique_unidad_torre_numero;
ALTER TABLE public.unidades ADD CONSTRAINT unique_unidad_torre_numero UNIQUE (organization_id, torre, numero);
ALTER TABLE public.verificacion_asamblea_sesiones DROP CONSTRAINT IF EXISTS verificacion_asamblea_sesiones_asamblea_id_fkey;
ALTER TABLE public.verificacion_asamblea_sesiones ADD CONSTRAINT verificacion_asamblea_sesiones_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.verificacion_asamblea_sesiones DROP CONSTRAINT IF EXISTS verificacion_asamblea_sesiones_pkey;
ALTER TABLE public.verificacion_asamblea_sesiones ADD CONSTRAINT verificacion_asamblea_sesiones_pkey PRIMARY KEY (id);
ALTER TABLE public.verificacion_asamblea_sesiones DROP CONSTRAINT IF EXISTS verificacion_asamblea_sesiones_pregunta_id_fkey;
ALTER TABLE public.verificacion_asamblea_sesiones ADD CONSTRAINT verificacion_asamblea_sesiones_pregunta_id_fkey FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) ON DELETE SET NULL;
ALTER TABLE public.verificacion_asistencia_registro DROP CONSTRAINT IF EXISTS verificacion_asistencia_regis_quorum_asamblea_id_pregunta_i_key;
ALTER TABLE public.verificacion_asistencia_registro ADD CONSTRAINT verificacion_asistencia_regis_quorum_asamblea_id_pregunta_i_key UNIQUE (quorum_asamblea_id, pregunta_id);
ALTER TABLE public.verificacion_asistencia_registro DROP CONSTRAINT IF EXISTS verificacion_asistencia_registro_asamblea_id_fkey;
ALTER TABLE public.verificacion_asistencia_registro ADD CONSTRAINT verificacion_asistencia_registro_asamblea_id_fkey FOREIGN KEY (asamblea_id) REFERENCES asambleas(id) ON DELETE CASCADE;
ALTER TABLE public.verificacion_asistencia_registro DROP CONSTRAINT IF EXISTS verificacion_asistencia_registro_pkey;
ALTER TABLE public.verificacion_asistencia_registro ADD CONSTRAINT verificacion_asistencia_registro_pkey PRIMARY KEY (id);
ALTER TABLE public.verificacion_asistencia_registro DROP CONSTRAINT IF EXISTS verificacion_asistencia_registro_pregunta_id_fkey;
ALTER TABLE public.verificacion_asistencia_registro ADD CONSTRAINT verificacion_asistencia_registro_pregunta_id_fkey FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) ON DELETE CASCADE;
ALTER TABLE public.verificacion_asistencia_registro DROP CONSTRAINT IF EXISTS verificacion_asistencia_registro_quorum_asamblea_id_fkey;
ALTER TABLE public.verificacion_asistencia_registro ADD CONSTRAINT verificacion_asistencia_registro_quorum_asamblea_id_fkey FOREIGN KEY (quorum_asamblea_id) REFERENCES quorum_asamblea(id) ON DELETE CASCADE;
ALTER TABLE public.votos DROP CONSTRAINT IF EXISTS votos_opcion_id_fkey;
ALTER TABLE public.votos ADD CONSTRAINT votos_opcion_id_fkey FOREIGN KEY (opcion_id) REFERENCES opciones_pregunta(id) ON DELETE CASCADE;
ALTER TABLE public.votos DROP CONSTRAINT IF EXISTS votos_pkey;
ALTER TABLE public.votos ADD CONSTRAINT votos_pkey PRIMARY KEY (id);
ALTER TABLE public.votos DROP CONSTRAINT IF EXISTS votos_poder_id_fkey;
ALTER TABLE public.votos ADD CONSTRAINT votos_poder_id_fkey FOREIGN KEY (poder_id) REFERENCES poderes(id);
ALTER TABLE public.votos DROP CONSTRAINT IF EXISTS votos_pregunta_id_fkey;
ALTER TABLE public.votos ADD CONSTRAINT votos_pregunta_id_fkey FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) ON DELETE CASCADE;
ALTER TABLE public.votos DROP CONSTRAINT IF EXISTS votos_pregunta_id_unidad_id_key;
ALTER TABLE public.votos ADD CONSTRAINT votos_pregunta_id_unidad_id_key UNIQUE (pregunta_id, unidad_id);
ALTER TABLE public.votos DROP CONSTRAINT IF EXISTS votos_unidad_id_fkey;
ALTER TABLE public.votos ADD CONSTRAINT votos_unidad_id_fkey FOREIGN KEY (unidad_id) REFERENCES unidades(id) ON DELETE CASCADE;
